# Generated by Django 4.2.4 on 2023-09-28 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Сoordinate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('imgs', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Картинка')),
                ('description_short', models.TextField()),
                ('description_long', models.TextField()),
                ('coordinates', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.сoordinate', verbose_name='Координаты')),
            ],
        ),
    ]
