# Generated by Django 4.2.4 on 2023-09-28 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Сoordinate',
            new_name='Coordinate',
        ),
    ]
