# Generated by Django 4.2.4 on 2023-09-28 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_rename_сoordinate_coordinate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='coordinates',
        ),
        migrations.AddField(
            model_name='place',
            name='lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='place',
            name='lon',
            field=models.FloatField(blank=True, null=True, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='place',
            name='description_long',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='description_short',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.DeleteModel(
            name='Coordinate',
        ),
    ]
