# Generated by Django 4.2.4 on 2023-10-04 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_remove_place_coordinates_place_lat_place_lon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='imgs',
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(blank=True, null=True, verbose_name='Порядковый номер')),
                ('img', models.ImageField(blank=True, upload_to='')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.place', verbose_name='Мероприятие')),
            ],
        ),
    ]
