# Generated by Django 4.2 on 2024-02-04 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_remove_place_imgs_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['num']},
        ),
        migrations.AlterField(
            model_name='image',
            name='num',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Порядковый номер'),
        ),
    ]
