# Generated by Django 4.2 on 2024-02-07 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_alter_image_options_alter_image_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='description_long',
            new_name='long_description',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='description_short',
            new_name='short_description',
        ),
        migrations.AlterField(
            model_name='place',
            name='title',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='place',
            unique_together={('lon', 'lat')},
        ),
    ]
