# Generated by Django 4.2 on 2024-02-07 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_alter_image_img_alter_image_num_alter_place_lat_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['order']},
        ),
        migrations.RenameField(
            model_name='image',
            old_name='num',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='title',
            new_name='place',
        ),
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.ImageField(upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='place',
            name='long_description',
            field=models.TextField(blank=True, verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='place',
            name='short_description',
            field=models.TextField(blank=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='place',
            name='title',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Название'),
        ),
    ]
