# Generated by Django 4.2 on 2024-02-07 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_alter_image_options_rename_num_image_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='order',
            field=models.IntegerField(blank=True, db_index=True, default=0, verbose_name='Порядковый номер'),
        ),
    ]
